spring:
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
    timeOfLife: 300000
  data:
    mongodb:
      database: proyectoFinal
      host: localhost
      port: 27017
jwt:
  expiration: 1800000
  secret: springbootjwtbackend
server:
  port: 8080